package com.innovu.visitor.model

data class VisitorRequest(
    val visitorID: Int,
    val visitorCode: String?,
    val visitorName: String,
    val studentID: Int,
    val visitorTypeID: Int,
    val startTime: String?,
    val endTime: String?,
    val venue: String?,
    val checkINtime: String?,
    val checkOutTime: String?,
    val meetingTypeID: Int,
    val parentContact: String,
    val checkinUserID: Int?,
    val approveUserID: Int?,
    val checkoutUserID: Int?,
    val operationDate: String,
    val smsStatus: String?,
    val smsResponse: String?,
    val recordStatusID: Int,
    val meetingUserID: Int,
    val note: String?,
    val branchID: Int,
    val organizationID: Int,
    val inGateID: Int?,
    val outGateID: Int?,
    val createdAt: String,
    val updatedAt: String,
    val cancelUserID: Int?,
    val cancelDatetime: String?,
    val qrPath: String?,
    val grNo:String?
)
